name: nextstrain_library_design
channels:
  - conda-forge
  - bioconda

dependencies:
  - mafft=7.505
  - nextclade
  - iqtree=2.2.0_beta
  - nextalign=2.14.0
  - python>=3.10*
  - csvtk
  - pip
  - pip:
    - nextstrain-augur==22.1.0